### ISSUE TITLE
Read and write of sbml

### ISSUE THREAD

**Issue by ghost** [PublicHealthEngland/pygom#3]
Ability to read (and write) a [SBML](http://sbml.org/Main_Page) document, translating it into a usable class will greatly improve 

1.. Reuse of existing model
2. Synchronization with other software

**Comment by twomagpi** [comment]
Not entirely clear that SBML is an appropriate carrier for model information. A simple serialisation schema is certainly required. Perhaps borrow the work from [Quilty](https://github.com/PublicHealthEngland/quilty/blob/master/quilty/data_model/model.py)

**Comment by twomagpi** [comment]
I think we should drow the existing SBML support from PyGOM and replace with a simple serialisation scheme as above.

**Comment by twomagpi** [comment]
This is quite a difficult one as I would like to support SBML but it is rather complex and although the `sbml_translate` sub-package does read SBML this is far from a clean solution and lacks tests and examples.

I think splitting this out of the core into a separate module is probably the correct way forward so that the core is not dependent on SBML and implementing a lightweight serialisation schema for PyGOM would be best. Conversoin to and from this schema and SBML would then be the role of that separate package.

**Comment by twomagpi** [comment]
Removed the SBML module to place in separate package
